import { ComponentPosition } from "../../../inventory/master-catalog/cars-catalog.dataset";

/**
 * Operational inspection progress for an individual target component.
 * Tells us IF the item was inspected, or if not, the operational reason.
 */
export type TargetInspectionStatus =
  | "NOT_INSPECTED"    // Pending inspection
  | "INSPECTED"        // Successfully physically inspected
  | "NOT_ACCESSIBLE"   // Physically obstructed / inaccessible (e.g. locked lug nut, jammed hood)
  | "NOT_APPLICABLE";  // Feature/component not present on this specific trim/model

/**
 * Technical condition/health of an inspected component.
 * Strictly defined only when status === "INSPECTED".
 */
export type InspectionCondition =
  | "GOOD"             // Within acceptable OEM/operational tolerances
  | "ATTENTION"        // Partial wear, weeping, or preventive maintenance needed soon
  | "CRITICAL";        // Dangerous wear, functional failure, or active safety hazard

/**
 * Technical urgency / risk severity of a detected finding.
 */
export type FindingSeverity = "CRITICAL" | "ATTENTION" | "INFO";

/**
 * Policy governing whether a recorded finding should be projected into the relational model Fault.
 * Prevents non-actionable observations or INFO items from polluting the Fault analytics table.
 */
export type FaultProjectionPolicy =
  | "ALWAYS"            // Always project (mandatory defect)
  | "WHEN_ACTIONABLE"   // Project only if severity is CRITICAL or ATTENTION
  | "NEVER";            // Informational observation only (never project to Fault)

/**
 * Standard finding definition in the catalog.
 */
export interface InspectionFindingDef {
  readonly key: string;                     // e.g. "PAD_THICKNESS_CRITICAL"
  readonly label: string;                   // English description
  readonly labelAr: string;                 // Arabic description
  readonly defaultSeverity: FindingSeverity; // Recommended severity
  readonly canonicalPartSlug: string;       // Target canonical component
  readonly faultProjectionPolicy?: FaultProjectionPolicy; // defaults to "WHEN_ACTIONABLE"
}

/**
 * Specific finding recorded on an inspection target result.
 * Combines structured catalog key with optional technician observation.
 */
export interface InspectionFinding {
  readonly id: string;
  readonly findingKey: string;
  readonly severity: FindingSeverity;
  readonly technicianObservation?: string;  // Freeform observation (e.g. "Inner pad worn to metal on passenger side")
  readonly recordedAt: string;
}

/**
 * Result of inspecting an individual component target on the vehicle.
 * Identity is composite and unique: targetKey + canonicalPartSlug + position.
 */
export interface InspectionTargetResult {
  readonly id: string;
  readonly targetKey: string;               // e.g. "FRONT_AXLE_BRAKES"
  readonly canonicalPartSlug: string;       // e.g. "brake-pads-front"
  readonly position: ComponentPosition;      // e.g. "FRONT"

  // Operational status vs Technical condition
  status: TargetInspectionStatus;
  condition?: InspectionCondition;           // Required when status === "INSPECTED", undefined otherwise

  // Inaccessibility or inapplicability explanation (required if NOT_ACCESSIBLE or NOT_APPLICABLE)
  nonInspectionReason?: string;

  // Recorded findings (can have 0 or more)
  findings: InspectionFinding[];
  technicianNote?: string;

  // Technical measurements (e.g. 1.5 mm, 11.8 V, 28 PSI)
  measurementValue?: number;
  measurementUnit?: string;

  mediaUrls?: string[];
  inspectedAt?: string;
  inspectedByStaffId?: string;
}

/**
 * Snapshot of a service recommendation generated by the suggestion engine.
 * Decoupled from future rule changes to guarantee immutable auditability.
 */
export interface GeneratedRecommendation {
  readonly id: string;
  readonly ruleId: string;
  readonly ruleVersion: number;
  readonly engineVersion: string;           // Engine version stamp (e.g. "v2.0-rules-engine")
  readonly targetResultId: string;
  readonly serviceKey: string;
  readonly serviceDisplayName: string;
  readonly recommendationLevel: "RECOMMENDED" | "RELATED" | "DIAGNOSTIC";
  readonly score: number;
  readonly generatedAt: string;
  readonly evaluationContext: {
    readonly findingKeys: readonly string[];
    readonly severities: readonly FindingSeverity[];
    readonly position: ComponentPosition;
  };
}

/**
 * Technician's explicit decision on a generated recommendation.
 * Tracks acceptance, dismissal reasons, and scope modification notes.
 * Does NOT permit direct price tampering by technicians.
 */
export type RecommendationDecisionStatus =
  | "PENDING"
  | "ACCEPTED"
  | "DISMISSED"
  | "MODIFIED_SCOPE";

export interface RecommendationDecision {
  readonly recommendationId: string;
  decision: RecommendationDecisionStatus;
  decidedAt?: string;
  dismissalReason?: string;                 // e.g. "Customer replaced pads 2 weeks ago"
  scopeModificationNote?: string;           // e.g. "Requires extensive hub de-rusting prior to rotor install"
}

/**
 * Overall lifecycle state of the Inspection Aggregate.
 */
export type InspectionLifecycleState =
  | "NOT_STARTED"
  | "IN_PROGRESS"
  | "COMPLETED"
  | "SUBMITTED"
  | "OPERATOR_REVIEW"
  | "LOCKED";

/**
 * Historical Target Snapshot item with presentation-ready labels.
 */
export interface SnapshotTargetItem {
  readonly targetResultId: string;
  readonly targetKey: string;
  readonly targetLabel: string;
  readonly canonicalPartSlug: string;
  readonly canonicalPartName: string;
  readonly position: ComponentPosition;
  readonly status: TargetInspectionStatus;
  readonly condition?: InspectionCondition;
  readonly nonInspectionReason?: string;
  readonly technicianNote?: string;
  readonly measurementDisplay?: string;
  readonly findings: readonly {
    readonly findingKey: string;
    readonly label: string;
    readonly labelAr: string;
    readonly severity: FindingSeverity;
    readonly technicianObservation?: string;
  }[];
}

/**
 * Historical Recommendation Snapshot item with presentation-ready labels.
 */
export interface SnapshotRecommendationItem {
  readonly recommendationId: string;
  readonly ruleId: string;
  readonly ruleVersion: number;
  readonly engineVersion: string;
  readonly serviceKey: string;
  readonly serviceDisplayName: string;
  readonly recommendationLevel: "RECOMMENDED" | "RELATED" | "DIAGNOSTIC";
  readonly score: number;
  readonly decision: RecommendationDecisionStatus;
  readonly dismissalReason?: string;
  readonly scopeModificationNote?: string;
}

/**
 * Immutable report snapshot generated upon inspection submission.
 * Completely frozen and presentation-ready without resolving against mutable external catalogs.
 */
export interface InspectionReportSnapshot {
  readonly snapshotId: string;
  readonly catalogVersion: number;
  readonly templateCode: string;
  readonly submittedAt: string;
  readonly submittedByStaffId: string;
  readonly targets: readonly SnapshotTargetItem[];
  readonly recommendations: readonly SnapshotRecommendationItem[];
  readonly findingsSummary: {
    readonly criticalCount: number;
    readonly attentionCount: number;
    readonly passedCount: number;
    readonly inaccessibleCount: number;
  };
  readonly acceptedServiceKeys: readonly string[];
}

/**
 * Full serialization shape stored inside Prisma `Inspection.fields`.
 */
export interface InspectionAggregateDocument {
  readonly schemaVersion: number;           // e.g. 2
  readonly aggregateVersion: number;        // Monotonically increasing version for Optimistic Concurrency Control (OCC)
  readonly catalogVersion: number;
  readonly templateCode: string;
  state: InspectionLifecycleState;
  targets: Record<string, InspectionTargetResult>; // keyed by targetResultId
  recommendations: GeneratedRecommendation[];
  decisions: RecommendationDecision[];
  startedAt: string;
  completedAt?: string;
  submittedAt?: string;
  technicianStaffId: string;
  snapshot?: InspectionReportSnapshot;
  // Quote items & read-model projections attached by technician or quote builder
  findings?: any[];
  parts?: Array<{
    inventoryItemId?: string;
    name: string;
    sku?: string;
    quantity: number;
    unitPrice: number;
  }>;
  services?: Array<{
    id?: string;
    name: string;
    laborPrice: number;
    hours?: number;
  }>;
  pricing?: {
    partsTotal: number;
    laborTotal: number;
    grandTotal: number;
  };
  note?: string;
  findingsSummary?: string;
  inspectionReport?: string;
  inspectionReportSubmitted?: boolean;
  operatorApproved?: boolean;
  approvedAt?: string;
  approvedBy?: string;
}
