export const PRODUCT_NAME = "MOP";

export const routeCatalog = [
  { id: "platform", label: "Workshops", permission: "platform.tenant.read", accountTypes: ["platform"] },
  { id: "platform-add-workshop", label: "Add Workshop Owner", permission: "platform.tenant.create", accountTypes: ["platform"] },
  { id: "platform-reports", label: "Platform Reports", permission: "reports.platform.workshops.view", accountTypes: ["platform"] },
  { id: "platform-live-view", label: "Workshop Live View", permission: "platform.tenant.read", accountTypes: ["platform"] },
  { id: "platform-control", label: "Super Admin Control", permission: "control.manage", accountTypes: ["platform"] },
  { id: "tenant", label: "Tenant", permission: "tenant.workspace.read", accountTypes: ["platform", "tenant_staff"] },
  { id: "workflow-health", label: "Workflow Health", permission: "operations.health.view", accountTypes: ["tenant_staff"] },
  { id: "pricing-catalog", label: "Pricing Catalog", permission: "finance.catalog.view", accountTypes: ["tenant_staff"] },
  { id: "financial-configuration", label: "Financial Configuration", permission: "finance.configuration.view", accountTypes: ["tenant_staff"] },
  { id: "financial-dashboard", label: "Financial Dashboard", permission: "finance.reports.view", accountTypes: ["tenant_staff"] },
  { id: "invoices-payments", label: "Invoices & Payments", permission: "finance.invoice.view", accountTypes: ["tenant_staff"] },
  { id: "discounts-refunds", label: "Discounts & Refunds", permission: "finance.refund.request", accountTypes: ["tenant_staff"] },
  { id: "branch-invoices", label: "Branch Invoices", permission: "finance.invoice.view", accountTypes: ["tenant_staff"] },
  { id: "customer-finance", label: "Invoice & Payment", permission: "finance.invoice.view", accountTypes: ["customer"] },
  { id: "builder-home", label: "Builder Home", permission: "builder.read", accountTypes: ["tenant_staff"] },
  { id: "builder-brand-theme", label: "Brand & Theme", permission: "builder.brand.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-page-builder", label: "Page Builder", permission: "builder.pages.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-role-experience", label: "Role Experience", permission: "builder.role_experience.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-workflow-feature", label: "Workflow & Features", permission: "builder.workflow.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-forms-fields", label: "Forms & Fields", permission: "builder.forms.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-messages-templates", label: "Messages & Templates", permission: "builder.messages.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-organization-access", label: "Organization & Access", permission: "builder.organization.edit", accountTypes: ["tenant_staff"] },
  { id: "builder-configuration-permissions", label: "Configuration & Permissions", permission: "configuration.permissions.view", accountTypes: ["tenant_staff"] },
  { id: "builder-publish-center", label: "Publish Center", permission: "builder.publish", accountTypes: ["tenant_staff"] },
  { id: "builder-audit-rollback", label: "Audit & Rollback", permission: "builder.rollback", accountTypes: ["tenant_staff"] },
  { id: "users-access", label: "Users & Access", permission: "tenant.users.read", accountTypes: ["platform", "tenant_staff"] },
  { id: "customers", label: "Customers", permission: "branch.customer.read", accountTypes: ["tenant_staff"] },
  { id: "customer-decisions", label: "Customer Decisions", permission: "customer_decision.view_staff", accountTypes: ["tenant_staff"] },
  { id: "branch", label: "Branch", permission: "branch.work_order.create", accountTypes: ["tenant_staff"] },
  { id: "branch-home", label: "Branch Home", permission: "branch.operations.view", accountTypes: ["tenant_staff"] },
  { id: "branch-intake", label: "Customer Intake", permission: "branch.intake.manage", accountTypes: ["tenant_staff"] },
  { id: "branch-work-orders", label: "Branch Work Orders", permission: "branch.operations.view", accountTypes: ["tenant_staff"] },
  { id: "branch-workspace", label: "Work Order Workspace", permission: "branch.operations.view", accountTypes: ["tenant_staff"] },
  { id: "branch-decisions", label: "Approvals & Decisions", permission: "customer_decision.view_staff", accountTypes: ["tenant_staff"] },
  { id: "branch-delivery", label: "Delivery & Payments", permission: "branch.delivery.view", accountTypes: ["tenant_staff"] },
  { id: "work-orders", label: "Work Orders", permission: "workorders.view", accountTypes: ["tenant_staff"] },
  { id: "quotations", label: "Quotations", permission: "quotation.recordDecision", accountTypes: ["tenant_staff"] },
  { id: "pos", label: "POS", permission: "pos.directSale", accountTypes: ["tenant_staff"] },
  { id: "billing", label: "Billing", permission: "branch.payment.record", accountTypes: ["tenant_staff"] },
  { id: "inventory", label: "Inventory", permission: "inventory.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-home", label: "Inventory Home", permission: "inventory.home.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-requests", label: "Technician Requests", permission: "inventory.requests.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-catalog", label: "Inventory POS Control", permission: "inventory.catalog.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-quantity", label: "Quantity Control", permission: "inventory.stock.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-returns", label: "Returns / Movements", permission: "inventory.stock.ledger.view", accountTypes: ["tenant_staff"] },
  { id: "inventory-reports", label: "Stock Insights", permission: "reports.inventory.view", accountTypes: ["tenant_staff"] },
  { id: "reports", label: "Reports", permission: "reports.company.view", accountTypes: ["tenant_staff"] },
  { id: "analytics-home", label: "Analytics Home", permission: "reports.company.view", accountTypes: ["tenant_staff"] },
  { id: "analytics-operations", label: "Operations Analytics", permission: "reports.branch.operations.view", accountTypes: ["tenant_staff"] },
  { id: "analytics-people", label: "People Performance", permission: "reports.team.technician_performance.view", accountTypes: ["tenant_staff"] },
  { id: "analytics-inventory-customer", label: "Inventory & Customer Decisions", permission: "reports.inventory.view", accountTypes: ["tenant_staff"] },
  { id: "control", label: "Control", permission: "control.manage", accountTypes: ["platform", "tenant_staff"] },
  { id: "permissions", label: "Permissions", permission: "permissions.manage", accountTypes: ["platform", "tenant_staff"] },
  { id: "technician", label: "Home", permission: "task.view_assigned", accountTypes: ["tenant_staff"] },
  { id: "my-work", label: "My Work", permission: "task.view_assigned", accountTypes: ["tenant_staff"] },
  { id: "work-card", label: "Work Card", permission: "task.view_assigned", accountTypes: ["tenant_staff"] },
  { id: "team-review", label: "Team Review", permission: "task.review", accountTypes: ["tenant_staff"] },
  { id: "audit", label: "Audit", permission: "audit.read", accountTypes: ["platform", "tenant_staff"] },
  { id: "customer", label: "Customer Portal", permission: "customer.portal.view", accountTypes: ["customer"] }
] as const;

export const defaultRolePages: Record<string, string[]> = {
  platform_super_admin: ["platform", "platform-add-workshop", "platform-reports", "platform-live-view", "platform-control", "audit"],
  tenant_owner: [
    "builder-home",
    "builder-brand-theme",
    "builder-page-builder",
    "builder-role-experience",
    "builder-workflow-feature",
    "builder-forms-fields",
    "builder-messages-templates",
    "builder-organization-access",
    "builder-configuration-permissions",
    "builder-publish-center",
    "builder-audit-rollback",
    "workflow-health",
    "pricing-catalog",
    "financial-configuration",
    "financial-dashboard",
    "invoices-payments",
    "discounts-refunds",
    "users-access",
    "customers",
    "customer-decisions",
    "work-orders",
    "inventory",
    "reports",
    "audit"
  ],
  tenant_admin: [
    "builder-home",
    "builder-brand-theme",
    "builder-page-builder",
    "builder-role-experience",
    "builder-workflow-feature",
    "builder-forms-fields",
    "builder-messages-templates",
    "builder-organization-access",
    "builder-configuration-permissions",
    "builder-publish-center",
    "builder-audit-rollback",
    "workflow-health",
    "pricing-catalog",
    "financial-configuration",
    "financial-dashboard",
    "invoices-payments",
    "discounts-refunds",
    "users-access",
    "customers",
    "customer-decisions",
    "work-orders",
    "inventory",
    "reports",
    "audit"
  ],
  branch_manager: ["branch-home", "branch-intake", "branch-work-orders", "branch-workspace", "branch-decisions", "branch-invoices", "branch-delivery"],
  technician: ["technician", "my-work", "work-card"],
  team_leader: ["work-orders", "team-review"],
  inventory_manager: ["inventory-home", "inventory-requests", "inventory-catalog", "inventory-quantity", "inventory-returns", "inventory-reports"],
  data_analyst: ["analytics-home", "analytics-operations", "analytics-people", "analytics-inventory-customer", "reports"],
  customer: ["customer", "customer-finance"]
};

export const defaultRoleEntryRoute: Record<string, string> = {
  platform_super_admin: "platform",
  tenant_owner: "builder-home",
  tenant_admin: "builder-home",
  branch_manager: "branch-home",
  technician: "technician",
  team_leader: "work-orders",
  inventory_manager: "inventory-home",
  data_analyst: "analytics-home",
  customer: "customer"
};
