import type { ComponentRegistryItem } from "./types";

function item(input: ComponentRegistryItem): ComponentRegistryItem {
  return input;
}

export const sectionRegistry: ComponentRegistryItem[] = [
  item({
    type: "current_job_card",
    label: "Current Job",
    description: "Technician's most urgent assigned task.",
    allowedPages: ["technician.home"],
    allowedRoles: ["technician"],
    forbiddenRoles: ["customer", "inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["task.view_assigned"],
    requiredFeatures: [],
    requiredData: ["task", "work_order", "asset"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { icon: "wrench", style: "hero" }
  }),
  item({
    type: "technician_work_queue",
    label: "My Work",
    description: "Assigned work list for the technician.",
    allowedPages: ["technician.home", "technician.my_work"],
    allowedRoles: ["technician"],
    forbiddenRoles: ["customer", "inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["task.view_assigned"],
    requiredFeatures: [],
    requiredData: ["assigned_tasks"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { showCount: true }
  }),
  item({
    type: "quick_service_card",
    label: "Quick Service",
    description: "Allowed shortcut for configured service types only.",
    allowedPages: ["technician.home", "technician.work_card"],
    allowedRoles: ["technician"],
    forbiddenRoles: ["customer", "inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["task.start"],
    requiredFeatures: ["quick_service.enabled"],
    requiredData: ["service_types"],
    removable: true,
    reorderable: true,
    duplicatable: false,
    safetyCritical: false,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { compact: true }
  }),
  item({
    type: "parts_lifecycle_panel",
    label: "Parts Lifecycle",
    description: "Request, arrival confirmation, use, and unused return controls.",
    allowedPages: ["technician.work_card", "inventory.requests", "branch.workspace"],
    allowedRoles: ["technician", "inventory_manager", "branch_manager"],
    forbiddenRoles: ["customer", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["parts.request"],
    requiredFeatures: ["inventory.parts_lifecycle"],
    requiredData: ["part_requests", "issued_items", "returns"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { arrivedConfirmationRequired: true, returnUnusedEnabled: true }
  }),
  item({
    type: "customer_decision_panel",
    label: "Customer Decision",
    description: "Create and monitor customer approval requests.",
    allowedPages: ["technician.work_card", "branch.decisions", "customer.portal.home"],
    allowedRoles: ["technician", "branch_manager", "customer"],
    forbiddenRoles: ["inventory_manager", "team_leader", "data_analyst"],
    requiredPermissions: ["customer_decision.create"],
    requiredFeatures: ["customer_decision.enabled"],
    requiredData: ["customer_decision_requests"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: true,
    customerVisible: true,
    internalOnly: false,
    defaultSettings: { showPrices: false, customerCopy: true }
  }),
  item({
    type: "critical_warning_acknowledgement",
    label: "Critical Warning",
    description: "Required acknowledgement for critical rejected work.",
    allowedPages: ["technician.work_card", "customer.portal.home"],
    allowedRoles: ["technician", "customer"],
    forbiddenRoles: ["inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["customer_decision.view_own"],
    requiredFeatures: ["customer_decision.critical_warning"],
    requiredData: ["critical_decision_items"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: true,
    customerVisible: true,
    internalOnly: false,
    defaultSettings: { acknowledgementRequired: true }
  }),
  item({
    type: "finish_gate_panel",
    label: "Finish Gate",
    description: "Blocks finish when decisions, blockers, parts, or inspections are unresolved.",
    allowedPages: ["technician.work_card"],
    allowedRoles: ["technician"],
    forbiddenRoles: ["customer", "inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["task.complete"],
    requiredFeatures: [],
    requiredData: ["finish_gate_checks"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { strict: true }
  }),
  item({
    type: "inventory_request_queue",
    label: "Technician Requests",
    description: "Inventory Manager queue for technician part requests.",
    allowedPages: ["inventory.home", "inventory.requests"],
    allowedRoles: ["inventory_manager"],
    forbiddenRoles: ["customer", "technician", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["inventory.requests.view"],
    requiredFeatures: ["inventory.parts_lifecycle"],
    requiredData: ["part_requests", "warehouses"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { showTransitState: true }
  }),
  item({
    type: "inventory_stock_alerts",
    label: "Stock Alerts",
    description: "Low, critical, and zero stock signals.",
    allowedPages: ["inventory.home", "inventory.quantity", "branch.home"],
    allowedRoles: ["inventory_manager", "branch_manager"],
    forbiddenRoles: ["customer", "technician", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["inventory.stock.view"],
    requiredFeatures: ["inventory.thresholds"],
    requiredData: ["warehouse_stock"],
    removable: true,
    reorderable: true,
    duplicatable: true,
    safetyCritical: false,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { animateZeroStock: true, compact: false }
  }),
  item({
    type: "branch_attention_cards",
    label: "Branch Attention",
    description: "Branch-wide operational attention cards.",
    allowedPages: ["branch.home"],
    allowedRoles: ["branch_manager"],
    forbiddenRoles: ["customer", "technician", "inventory_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["branch.operations.view"],
    requiredFeatures: [],
    requiredData: ["work_orders", "branch_scope"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { showCriticalFirst: true }
  }),
  item({
    type: "customer_status_summary",
    label: "Service Status",
    description: "Customer-safe work order status summary.",
    allowedPages: ["customer.portal.home"],
    allowedRoles: ["customer"],
    forbiddenRoles: ["technician", "inventory_manager", "branch_manager", "team_leader", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["customer.portal.view"],
    requiredFeatures: ["customer_portal.enabled"],
    requiredData: ["customer_safe_work_order_summary"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: true,
    customerVisible: true,
    internalOnly: false,
    defaultSettings: { showBranchName: true }
  }),
  item({
    type: "safe_history_timeline",
    label: "Safe History",
    description: "Customer-safe asset history without old-owner private data.",
    allowedPages: ["customer.portal.home", "work_order.workspace"],
    allowedRoles: ["customer", "branch_manager"],
    forbiddenRoles: ["inventory_manager", "technician", "team_leader", "data_analyst"],
    requiredPermissions: ["customer.history.view_safe"],
    requiredFeatures: ["customer_portal.enabled"],
    requiredData: ["safe_asset_history"],
    removable: true,
    reorderable: true,
    duplicatable: false,
    safetyCritical: false,
    customerSafe: true,
    customerVisible: true,
    internalOnly: false,
    defaultSettings: { hideOldOwnerData: true }
  }),
  item({
    type: "team_review_queue",
    label: "Team Review",
    description: "Team Leader review and rework queue.",
    allowedPages: ["team_leader.home"],
    allowedRoles: ["team_leader"],
    forbiddenRoles: ["customer", "technician", "inventory_manager", "branch_manager", "tenant_admin", "tenant_owner", "data_analyst"],
    requiredPermissions: ["task.review"],
    requiredFeatures: ["team_leader.review"],
    requiredData: ["review_queue", "assigned_technicians"],
    removable: false,
    reorderable: true,
    duplicatable: false,
    safetyCritical: true,
    customerSafe: false,
    customerVisible: false,
    internalOnly: true,
    defaultSettings: { scope: "assigned_technicians" }
  })
];

export const sectionRegistryByType = Object.fromEntries(sectionRegistry.map((entry) => [entry.type, entry])) as Record<string, ComponentRegistryItem>;
