import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import type { Observable } from 'rxjs';

/**
 * Money is a STRING everywhere in this file, and must stay one.
 *
 * Typing any of these as `number` would undo the whole phase: the value
 * would go through a float the moment Angular parsed the JSON, and
 * `1800.50` would become something that prints right and adds up wrong.
 */
export type Money = string;

export interface JobTotalLine {
  readonly id: string;
  readonly name: string;
  readonly quantity: number;
  readonly unitPrice: Money;
  readonly labour: Money;
  readonly total: Money;
}

export interface JobTotal {
  readonly subtotal: Money;
  readonly discount: Money;
  readonly tax: Money;
  readonly total: Money;
  readonly lines: readonly JobTotalLine[];
}

export interface Settlement {
  readonly invoiceId: string;
  readonly total: Money;
  readonly paid: Money;
  readonly outstanding: Money;
  readonly overpaid: Money;
  readonly settled: boolean;
}

export interface RefundApprovalRow {
  readonly id: string;
  readonly invoiceId: string;
  readonly invoiceNumber: string;
  readonly invoiceTotal: Money;
  readonly workOrderId: string;
  readonly identifier: string;
  readonly customerName: string;
  readonly amount: Money;
  readonly reason: string;
  readonly reasonCategory: string;
  readonly requestedBy: string;
  readonly requestedAt: string;
}

export interface DiscountApprovalRow {
  readonly id: string;
  readonly workOrderId: string;
  readonly identifier: string;
  readonly customerName: string;
  readonly amount: Money;
  readonly reason: string;
  readonly requestedBy: string;
  readonly requestedAt: string;
}

export interface MoneyApprovals {
  readonly refunds: readonly RefundApprovalRow[];
  readonly discounts: readonly DiscountApprovalRow[];
  readonly canDecideRefunds: boolean;
  readonly canDecideDiscounts: boolean;
}

@Injectable({ providedIn: 'root' })
export class FinanceApi {
  private readonly http = inject(HttpClient);

  /**
   * Turn a finished job into the invoice it will be paid against.
   *
   * There was no caller for this endpoint anywhere in the web app, which
   * made the last third of the journey unreachable: a job sits in
   * PAYMENT_PENDING, the delivery board correctly reports "The final invoice
   * has not been issued", the take-payment page needs an invoice id that
   * does not exist, and DELIVER is gated on `invoice.issued`. So no work
   * order could reach CLOSED through the product at all.
   *
   * Discount and tax are optional and omitted here: the workshop's
   * FinanceConfiguration supplies the defaults, and a page that made the
   * counter retype them every time would be inviting a different bug.
   */
  issueInvoice(workOrderId: string): Observable<Settlement> {
    return this.http.post<Settlement>(`/api/v1/finance/work-orders/${workOrderId}/invoice`, {});
  }

  jobTotal(workOrderId: string): Observable<JobTotal> {
    return this.http.get<JobTotal>(`/api/v1/finance/work-orders/${workOrderId}/total`);
  }

  settlement(invoiceId: string): Observable<Settlement> {
    return this.http.get<Settlement>(`/api/v1/finance/invoices/${invoiceId}`);
  }

  /**
   * The idempotency key is generated by the CALLER and reused across
   * retries of the same attempt. Generating it here, per call, would
   * defeat the entire mechanism -- two taps would produce two keys and
   * two payments.
   */
  pay(invoiceId: string, amount: Money, method: string, idempotencyKey: string): Observable<Settlement> {
    return this.http.post<Settlement>(`/api/v1/finance/invoices/${invoiceId}/payments`, {
      amount,
      method,
      idempotencyKey,
    });
  }

  /**
   * Everything about money waiting on a decision.
   *
   * Both loops behind this -- refunds and discounts -- could be requested and
   * decided over HTTP since Phase 8 and were reachable from no page at all.
   * The endpoints existed, were permission-gated, produced real credit notes,
   * and nothing in the product ever called them.
   */
  moneyApprovals(): Observable<MoneyApprovals> {
    return this.http.get<MoneyApprovals>('/api/v1/finance/approvals');
  }

  /**
   * Ask for money to go back to the customer.
   *
   * A request on its own moves nothing: approval is what produces the credit
   * note. That separation is why this is a request and not a "refund" button.
   */
  requestRefund(invoiceId: string, amount: Money, reason: string): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(`/api/v1/finance/invoices/${invoiceId}/refunds`, { amount, reason });
  }

  approveRefund(refundId: string): Observable<{ id: string; creditNoteNumber: string }> {
    return this.http.post<{ id: string; creditNoteNumber: string }>(`/api/v1/finance/refunds/${refundId}/approve`, {});
  }

  rejectRefund(refundId: string, reason: string): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(`/api/v1/finance/refunds/${refundId}/reject`, { reason });
  }

  /**
   * Ask to take money off a job before it is invoiced.
   *
   * The amount is a money string, not a percentage: what the workshop's
   * DISCOUNT_AUTHORITY policy compares against its threshold is the amount,
   * and asking the counter for a percentage would mean two different numbers
   * describing one concession.
   */
  requestDiscount(workOrderId: string, amount: Money, reason: string): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(`/api/v1/finance/work-orders/${workOrderId}/discounts`, { amount, reason });
  }

  approveDiscount(discountId: string): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(`/api/v1/finance/discounts/${discountId}/approve`, {});
  }

  rejectDiscount(discountId: string, reason: string): Observable<{ id: string }> {
    return this.http.post<{ id: string }>(`/api/v1/finance/discounts/${discountId}/reject`, { reason });
  }
}
