import { HttpClient } from '@angular/common/http';
import { Injectable, inject } from '@angular/core';
import type { Observable } from 'rxjs';

/**
 * Money is a STRING everywhere in this file, and must stay one.
 *
 * Typing any of these as `number` would undo the whole phase: the value
 * would go through a float the moment Angular parsed the JSON, and
 * `1800.50` would become something that prints right and adds up wrong.
 */
export type Money = string;

export interface JobTotalLine {
  readonly id: string;
  readonly name: string;
  readonly quantity: number;
  readonly unitPrice: Money;
  readonly labour: Money;
  readonly total: Money;
}

export interface JobTotal {
  readonly subtotal: Money;
  readonly discount: Money;
  readonly tax: Money;
  readonly total: Money;
  readonly lines: readonly JobTotalLine[];
}

export interface Settlement {
  readonly invoiceId: string;
  readonly total: Money;
  readonly paid: Money;
  readonly outstanding: Money;
  readonly overpaid: Money;
  readonly settled: boolean;
}

@Injectable({ providedIn: 'root' })
export class FinanceApi {
  private readonly http = inject(HttpClient);

  jobTotal(workOrderId: string): Observable<JobTotal> {
    return this.http.get<JobTotal>(`/api/v1/finance/work-orders/${workOrderId}/total`);
  }

  settlement(invoiceId: string): Observable<Settlement> {
    return this.http.get<Settlement>(`/api/v1/finance/invoices/${invoiceId}`);
  }

  /**
   * The idempotency key is generated by the CALLER and reused across
   * retries of the same attempt. Generating it here, per call, would
   * defeat the entire mechanism -- two taps would produce two keys and
   * two payments.
   */
  pay(invoiceId: string, amount: Money, method: string, idempotencyKey: string): Observable<Settlement> {
    return this.http.post<Settlement>(`/api/v1/finance/invoices/${invoiceId}/payments`, {
      amount,
      method,
      idempotencyKey,
    });
  }
}
