export interface InspectableSubsystem {
  id: string;
  nameEn: string;
  nameAr: string;
  systemCategoryEn: string;
  systemCategoryAr: string;
  icon: string;
  color: string;
  glowColor: string;
  // Percentage coordinates on the studio car render (0..100)
  hotspotPct: { x: number; y: number };
  // Card offset relative to hotspot (px)
  cardOffset: { x: number; y: number };
  symptoms: Array<{ en: string; ar: string }>;
  descriptionEn: string;
  descriptionAr: string;
}

export type CarSubsystemConfig = InspectableSubsystem;

export const CAR_SUBSYSTEMS: InspectableSubsystem[] = [
  {
    id: 'engine',
    nameEn: 'Engine Powertrain',
    nameAr: 'المحرك',
    systemCategoryEn: 'Combustion & Power Generation',
    systemCategoryAr: 'وحدة توليد القدرة والاحتراق',
    icon: '⚙️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 30, y: 39 },
    cardOffset: { x: -30, y: -90 },
    symptoms: [
      { en: 'Check Engine warning light illuminated', ar: 'لمبة فحص المحرك مضيئة' },
      { en: 'Engine idling rough, shuddering, or misfiring', ar: 'تنتيشة واهتزاز في دوران السلانسيه' },
      { en: 'Metallic clicking or knocking under acceleration', ar: 'صوت نقر أو تكتكة معدنية مع التسارع' },
      { en: 'Sudden loss of acceleration and sluggish power', ar: 'ضعف السحب والتسارع وعزم المحرك' },
      { en: 'Blue or black exhaust smoke with high oil burn', ar: 'دخان أزرق أو أسود من العادم واستهلاك زيت' },
    ],
    descriptionEn: 'Inspect spark plugs, ignition coils, cylinder compression, and fuel injector timing.',
    descriptionAr: 'فحص البواجي، المباين، كبس البساتم، وحساسات الرشاشات وشكمان العادم.',
  },
  {
    id: 'transmission',
    nameEn: 'Transmission & Gearbox',
    nameAr: 'ناقل الحركة',
    systemCategoryEn: 'Gearbox & Drivetrain Transfer',
    systemCategoryAr: 'صندوق التروس ونقل العزم',
    icon: '⚙️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 67, y: 55 },
    cardOffset: { x: 50, y: -80 },
    symptoms: [
      { en: 'Hard shifting, clunking, or delayed gear engagement', ar: 'نتعة أو تأخير وطقة في نقلات الجير' },
      { en: 'Transmission slipping out of gear under load', ar: 'تفويت أو انزلاق وفقدان التعشيق عند الضغط' },
      { en: 'Burnt transmission fluid smell or red fluid leaks', ar: 'رائحة حريق أو تسريب زيت القير' },
      { en: 'High-pitched whining or humming noise at speed', ar: 'صوت ونّة أو أنين متصاعد أثناء القيادة' },
      { en: 'Delayed response when shifting to Reverse or Drive', ar: 'تأخر استجابة الجير عند وضعه في R أو D' },
    ],
    descriptionEn: 'Check transmission fluid level, solenoid valve operation, torque converter, and clutch wear.',
    descriptionAr: 'فحص مستوى وجودة زيت القير، بلوف التحكم الهيدروليكي، وعمود الكردان.',
  },
  {
    id: 'brakes',
    nameEn: 'Brake System & ABS',
    nameAr: 'نظام الفرامل',
    systemCategoryEn: 'Hydraulic Braking & Safety',
    systemCategoryAr: 'الديسكات وتيل الفرامل ومنظومة ABS',
    icon: '🔘',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 51, y: 68 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'High-pitched squealing or grinding noise on braking', ar: 'صوت صفارة حادة أو احتكاك حديد عند الفرملة' },
      { en: 'Soft, spongy, or sinking brake pedal', ar: 'دواسة الفرامل خفيفة إسفنجية أو تغطس للأسفل' },
      { en: 'Steering wheel or pedal vibration during braking', ar: 'رعشة في الطارة أو دواسة الفرامل عند التهدئة' },
      { en: 'Vehicle pulls hard to one side when stopping', ar: 'انحراف وسحب السيارة لجهة واحدة عند الفرملة' },
      { en: 'Brake fluid low warning or ABS icon illuminated', ar: 'إضاءة لمبة سائل الفرامل أو لمبة ABS' },
    ],
    descriptionEn: 'Check front & rear brake pads thickness, rotor runout, and hydraulic lines.',
    descriptionAr: 'قياس سمك تيل الفرامل، فحص الطنابير، ومستوى زيت الفرامل.',
  },
  {
    id: 'cooling',
    nameEn: 'Cooling System & Radiator',
    nameAr: 'نظام التبريد',
    systemCategoryEn: 'Thermal Management & Radiator Loop',
    systemCategoryAr: 'الرادياتير ودورة سائل التبريد',
    icon: '🌡️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 19, y: 53 },
    cardOffset: { x: -20, y: -85 },
    symptoms: [
      { en: 'Engine temperature gauge rising into the red zone', ar: 'مؤشر حرارة المحرك يرتفع نحو المنطقة الحمراء' },
      { en: 'Coolant puddle leaking under front bumper', ar: 'تسريب مياه خضراء أو حمراء أسفل مقدمة السيارة' },
      { en: 'Radiator cooling fan running non-stop at high speed', ar: 'مروحة التبريد تعمل بأعلى سرعة باستمرار' },
      { en: 'Visible steam or sweet odor emerging from hood', ar: 'تصاعد بخار ماء أو رائحة سائل تبريد من الكبوت' },
      { en: 'Cabin heater blowing cold air despite warm engine', ar: 'دفاية السيارة تخرج هواء بارداً رغم سخونة المحرك' },
    ],
    descriptionEn: 'Check radiator core integrity, electric fan motor, thermostat valve, and water pump seal.',
    descriptionAr: 'فحص خلو الرادياتير من التسريب، كفاءة طلمبة المياه، وثرموستات الكوع.',
  },
  {
    id: 'ac',
    nameEn: 'A/C & Climate Control',
    nameAr: 'مكيف',
    systemCategoryEn: 'Refrigerant Loop & Cabin HVAC',
    systemCategoryAr: 'نظام التبريد والتكييف',
    icon: '❄️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 38, y: 57 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'A/C blowing warm or room temperature air', ar: 'المكيف يخرج هواء ساخناً أو غير بارد' },
      { en: 'Weak airflow from dashboard vents on high speed', ar: 'دفع الهواء ضعيف جداً من فتحات المكيف' },
      { en: 'Loud rattling or grinding from A/C compressor', ar: 'صوت خشونة أو طقطقة عند تشغيل كمبروسر المكيف' },
      { en: 'Musty, moldy, or stale odor inside cabin', ar: 'رائحة رطوبة أو عفن كريهة مع تشغيل التكييف' },
      { en: 'Water dripping onto front passenger footwell', ar: 'تسريب وتنقيط مياه داخل دواسة الراكب الأمامي' },
    ],
    descriptionEn: 'Inspect condenser, compressor clutch, refrigerant pressure, and cabin pollen filter.',
    descriptionAr: 'فحص سربنتينة التكييف، كمبروسر الفريون، وضغط الغاز، وفلتر الهواء الداخلي.',
  },
  {
    id: 'electrical',
    nameEn: 'Battery & Electrical System',
    nameAr: 'الكهرباء',
    systemCategoryEn: '12V Electrical, Battery & Alternator',
    systemCategoryAr: 'البطارية والمولد والدوائر الكهربائية',
    icon: '⚡',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 35, y: 45 },
    cardOffset: { x: -40, y: -80 },
    symptoms: [
      { en: 'Slow engine cranking or clicking when starting', ar: 'صعوبة وتأخر دوران المارش أو صوت تكتكة' },
      { en: 'Battery warning icon remains lit on dashboard', ar: 'لمبة البطارية / الدينامو مضيئة في الطبلون' },
      { en: 'Headlights and instrument cluster dimming or flickering', ar: 'ضعف ورعشة في إضاءة الأنوار الأمامية والشاشات' },
      { en: 'Battery drains completely after parking overnight', ar: 'تفريغ وفقدان شحن البطارية بعد التوقف' },
      { en: 'Heavy green or white corrosion on battery terminals', ar: 'تراكم أملاح وتآكل كبريتي على أقطاب البطارية' },
    ],
    descriptionEn: 'Measure cold crank amperage, terminal corrosion, alternator charging output, and fuses.',
    descriptionAr: 'قياس كفاءة شحن الدينامو، فحص أقطاب البطارية، والتأكد من عدم وجود تفريغ كهربائي.',
  },
  {
    id: 'suspension',
    nameEn: 'Suspension & Struts',
    nameAr: 'التعليق',
    systemCategoryEn: 'Shock Absorption & Dampers',
    systemCategoryAr: 'المساعدات والمقصات ونظام الثبات',
    icon: '🔩',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 48, y: 44 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Loud knocking or clunking over road bumps', ar: 'خبط وطقطقة مكتومة أسفل السيارة عند المطبات' },
      { en: 'Excessive car body bounce, diving, or swaying', ar: 'عوم ومرجحة مستمرة للسيارة وانخفاض المقدمة' },
      { en: 'Visible oil leaking or misting on strut body', ar: 'تسريب وترشيح زيت هيدروليك على جسم المساعد' },
      { en: 'Vehicle sagging lower on one side or corner', ar: 'هبوط وميل السيارة من زاوية واحدة' },
      { en: 'Uneven or cupped tire tread wear pattern', ar: 'تآكل غير متساوي ومتموج في نقشة الكاوتش' },
    ],
    descriptionEn: 'Inspect front MacPherson struts, rear coil springs, bushings, ball joints, and tie rods.',
    descriptionAr: 'فحص المساعدين الأمامية والخلفية، جلب المقصات، بارات الدركسيون، وميزان الاتزان.',
  },
  {
    id: 'steering',
    nameEn: 'Steering System & Alignment',
    nameAr: 'نظام التوجيه',
    systemCategoryEn: 'Rack, Pinion & Power Steering',
    systemCategoryAr: 'الدركسيون والعلبة وميزان التوجيه',
    icon: '🎯',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 55, y: 40 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Steering wheel heavy or stiff to turn while parking', ar: 'ثقل وصعوبة في لف الدركسيون أثناء المناورة والركن' },
      { en: 'Vehicle pulls or drifts to left or right constantly', ar: 'انحراف وسحب السيارة يميناً أو يساراً في الطرق' },
      { en: 'Whining or groaning noise when steering to full lock', ar: 'صوت ونّة أو أنين عند لف عجلة القيادة للنهاية' },
      { en: 'Excessive play or looseness in steering wheel', ar: 'بوش وفضاوه زائدة في حركة الطارة قبل الاستجابة' },
      { en: 'Steering wheel vibration felt at highway speeds', ar: 'رعشة مستمرة في الدركسيون عند سرعات الطرق السريعة' },
    ],
    descriptionEn: 'Check power steering fluid level, rack and pinion seals, tie rod ends, and wheel alignment.',
    descriptionAr: 'فحص علبة الدركسيون، بارات ومفصلات التوجيه، وزيت الباور، وميزان الزوايا.',
  },
  {
    id: 'exhaust',
    nameEn: 'Exhaust & Emissions',
    nameAr: 'نظام العادم',
    systemCategoryEn: 'Muffler, Pipes & Catalytic Converter',
    systemCategoryAr: 'الشكمان ودبة البيئة ومنظومة العادم',
    icon: '💨',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 80, y: 65 },
    cardOffset: { x: -40, y: -80 },
    symptoms: [
      { en: 'Loud roaring, hissing, or buzzing underneath car', ar: 'صوت هواء عالي أو هدرة وضجيج صاخب من أسفل السيارة' },
      { en: 'Strong sulfur, rotten egg, or raw exhaust odor', ar: 'رائحة كبريت أو بنزين نيء نافذة من العادم' },
      { en: 'Catalytic converter efficiency warning light active', ar: 'إضاءة لمبة فحص المحرك لكفاءة دبة التلوث / البيئة' },
      { en: 'Rattling metal vibration noise from exhaust muffler', ar: 'صوت شخاليل أو تكتكة معدنية داخل علبة الشكمان' },
      { en: 'Visible rust holes, cracks, or hanging exhaust pipe', ar: 'صدأ وثقوب واضحة أو تدلي ماسورة الشكمان' },
    ],
    descriptionEn: 'Inspect catalytic converter efficiency, muffler integrity, exhaust manifold gaskets, and hanger brackets.',
    descriptionAr: 'فحص دبة الرصاص، خلو مواسير العادم من التنفيس، وسلامة كراسي الشكمان.',
  },
  {
    id: 'tires',
    nameEn: 'Tires & Wheels',
    nameAr: 'الإطارات والجنوط',
    systemCategoryEn: 'Rubber, Rims & Pressure Monitoring',
    systemCategoryAr: 'الكاوتش والجنوط ونظام ضغط الهواء',
    icon: '🛞',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 26, y: 68 },
    cardOffset: { x: -30, y: -75 },
    symptoms: [
      { en: 'TPMS low tire pressure warning light flashing', ar: 'إضاءة مؤشر تحذير ضغط الإطارات بالطبلون' },
      { en: 'Visible tire sidewall bubble, bulge, or deep crack', ar: 'ظهور انتفاخ أو شق عميق في جانب الإطار' },
      { en: 'Tire tread worn smooth past safety wear indicator bars', ar: 'تآكل مداس الإطار واختفاء النقشة' },
      { en: 'Slow air leak requiring weekly re-inflation', ar: 'فقدان بطيء ومستمر للهواء يحتاج تزويد أسبوعي' },
      { en: 'Bent or cracked alloy wheel rim causing wheel wobble', ar: 'اعوجاج أو كسر في حافة الجنط يسبب رفة واهتزاز' },
    ],
    descriptionEn: 'Inspect tire tread depth, sidewall integrity, wheel rim runout, and balance.',
    descriptionAr: 'قياس عمق نقشة الكاوتش، سلامة جدران الإطار، فحص استقامة الجنط وترصيص العجل.',
  },
  {
    id: 'fuel',
    nameEn: 'Fuel System & Injectors',
    nameAr: 'دورة الوقود',
    systemCategoryEn: 'Pump, Lines & Injector Nozzles',
    systemCategoryAr: 'طلمبة البنزين والرشاشات وفلتر الوقود',
    icon: '⛽',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 42, y: 48 },
    cardOffset: { x: 40, y: -75 },
    symptoms: [
      { en: 'Noticeable drop in fuel economy / high consumption', ar: 'استهلاك غير طبيعي للبنزين ونقص سريع في الوقود' },
      { en: 'Engine sputters or cuts out under hard acceleration', ar: 'تأتأة وكتمة وتقطيع واضح في المحرك عند التسارع' },
      { en: 'High-pitched fuel pump whining from rear seat area', ar: 'صوت ونّة أو صفير كهربائي من طلمبة البنزين بالخلف' },
      { en: 'Strong raw gasoline odor inside or outside car', ar: 'رائحة وقود أو بنزين خام قوية داخل أو حول السيارة' },
      { en: 'Extended cranking or hard starting when engine is hot', ar: 'صعوبة وتأخر شديد في تشغيل المحرك وهو ساخن' },
    ],
    descriptionEn: 'Test fuel rail pressure, fuel pump flow rate, filter restriction, and fuel injector spray patterns.',
    descriptionAr: 'قياس ضغط مسطرة البنزين، كفاءة طلمبة الوقود، وفحص نظافة الرشاشات وفلتر البنزين.',
  },
  {
    id: 'fluids',
    nameEn: 'Fluids & Maintenance',
    nameAr: 'الزيوت والفلاتر',
    systemCategoryEn: 'Lubrication, Filtration & Scheduled Service',
    systemCategoryAr: 'التزييت والترشيح والصيانة الدورية',
    icon: '🛢️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 34, y: 52 },
    cardOffset: { x: -30, y: -80 },
    symptoms: [
      { en: 'Engine oil level low or past recommended kilometer interval', ar: 'انخفاض مستوى الزيت أو تجاوز موعد الكيلومتر' },
      { en: 'Oil color is pitch black, thick, or contains gritty residue', ar: 'لون الزيت أسود داكن جداً ولزج أو به شوائب' },
      { en: 'Maintenance Service Due wrench indicator illuminated', ar: 'إضاءة لمبة الصيانة الدورية أو علامة المفتاح' },
      { en: 'Air filter heavily clogged with dust, sand, or leaves', ar: 'انسداد شديد في فلتر هواء المحرك بالأتربة' },
      { en: 'Fresh oil drips or damp residue on lower engine cover', ar: 'ترشيح أو تنقيط قطرات زيت طازجة أسفل المحرك' },
    ],
    descriptionEn: 'Check engine oil viscosity, oil filter, air intake filter, and all fluid levels.',
    descriptionAr: 'فحص لزوجة زيت المحرك، فلتر الزيت، فلتر الهواء، ومستويات كافة سوائل السيارة.',
  },
  {
    id: 'ignition',
    nameEn: 'Ignition & Starter System',
    nameAr: 'نظام الإشعال والمارش',
    systemCategoryEn: 'Starter Motor, Coils & Spark Plugs',
    systemCategoryAr: 'المارش، البواجي، ومباين الإشعال',
    icon: '⚡',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 28, y: 36 },
    cardOffset: { x: -35, y: -80 },
    symptoms: [
      { en: 'Rapid clicking sound when turning key or pressing start button', ar: 'صوت طقطقة سريعة عند محاولة تشغيل السيارة' },
      { en: 'Starter motor spins with grinding noise but engine does not engage', ar: 'المارش يدور بصوت خشونة حاد دون تدوير المحرك' },
      { en: 'Engine misfires or stumbles under heavy acceleration or uphill', ar: 'تنتيش وتقطيع في المحرك عند الصعود أو الضغط القوي' },
      { en: 'Worn or fouled spark plug electrodes causing high fuel waste', ar: 'تآكل شمعات الاحتراق مسبباً ضعف العزم وزيادة الاستهلاك' },
      { en: 'Keyless push-button start intermittent or key fob not detected', ar: 'زر التشغيل الذكي لا يستجيب من المحاولة الأولى' },
    ],
    descriptionEn: 'Inspect starter solenoid draw, ignition coil pack primary/secondary resistance, and spark plug gaps.',
    descriptionAr: 'فحص ملف المارش، مقاومة مباين الإشعال، وخلوص شمعات الاحتراق.',
  },
  {
    id: 'lighting',
    nameEn: 'Headlights & Exterior Lighting',
    nameAr: 'الإضاءة والأنوار الخارجية',
    systemCategoryEn: 'Headlamps, Indicators & Brake Lights',
    systemCategoryAr: 'المصابيح الأمامية، الإشارات، ولمبات الفرامل',
    icon: '💡',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 15, y: 46 },
    cardOffset: { x: -20, y: -85 },
    symptoms: [
      { en: 'Headlamp bulb burned out or dim low/high beam output', ar: 'احتراق لمبة المصباح الأمامي أو ضعف شديد في الإضاءة' },
      { en: 'Fast blinking turn signal indicator on dashboard (hyper-flash)', ar: 'فلاشر إشارة الانعطاف يومض بسرعة غير طبيعية' },
      { en: 'Brake lamps not illuminating when pedal is pressed', ar: 'لمبات الفرامل الخلفية لا تضيء عند الضغط على الدواسة' },
      { en: 'Cloudy, yellowed, or fogged headlamp plastic lenses', ar: 'اصفرار وتعتيم في زجاج الكشافات الأمامية يحجب الرؤية' },
      { en: 'Daytime running light (DRL) or fog lamp inoperative', ar: 'تعطل لمبات الضباب أو مصابيح الإضاءة النهارية' },
    ],
    descriptionEn: 'Check headlight alignment, LED/HID modules, tail light assemblies, turn signals, and brake switch.',
    descriptionAr: 'فحص ميزان الكشافات، كفاءة لمبات LED، الإشارات، وحساس لمبة الفرامل.',
  },
  {
    id: 'glass_wipers',
    nameEn: 'Windshield, Wipers & Mirrors',
    nameAr: 'الزجاج والمساحات والمرايا',
    systemCategoryEn: 'Glass, Blades, Washers & Mirrors',
    systemCategoryAr: 'الزجاج الأمامي، شفرات المساحات، والمرايا الجانبية',
    icon: '🪟',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 46, y: 26 },
    cardOffset: { x: 40, y: -75 },
    symptoms: [
      { en: 'Stone chip or spreading crack on front windshield glass', ar: 'نقرة حجر أو شرخ ممتد في الزجاج الأمامي' },
      { en: 'Wiper blades streaking, chattering, or skipping across glass', ar: 'ريش المساحات تترك خطوطاً وتصدر صوتاً مزعجاً' },
      { en: 'Windshield washer pump not spraying cleaning fluid', ar: 'رشاشات مياه المساحات مسدودة أو المضخة لا تضخ' },
      { en: 'Side mirror power folding or electric glass adjustment stuck', ar: 'محرك طي المرايا الجانبية أو ضبط الزجاج معطل' },
      { en: 'Rear window defroster electric grid lines failing to clear frost', ar: 'خطوط سخان الزجاج الخلفي لا تزيل الضباب والجليد' },
    ],
    descriptionEn: 'Inspect windshield chip integrity, wiper motor linkage, washer jets, and side mirror actuators.',
    descriptionAr: 'فحص سلامة الزجاج، ميكانيزم المساحات، رشاشات المياه، ومحركات المرايا.',
  },
  {
    id: 'interior',
    nameEn: 'Cabin Interior & Seats',
    nameAr: 'المقصورة والفرش الداخلي',
    systemCategoryEn: 'Seats, Upholstery, Belts & Trim',
    systemCategoryAr: 'المقاعد، الفرش، أحزمة الأمان، وديكورات المقصورة',
    icon: '💺',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 58, y: 35 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Power seat adjustment motor jammed, slow, or unresponsive', ar: 'محرك تعديل مقعد السائق الكهربائي عالق أو لا يتحرك' },
      { en: 'Seatbelt retractor sluggish, jammed, or failing to lock on pull', ar: 'حزام الأمان بطيء في الارتداد أو لا يقفل عند الشد المفاجئ' },
      { en: 'Persistent squeaks, creaks, or rattles from dashboard trim', ar: 'أصوات صرير وطقطقة مستمرة من ديكورات الطبلون والأبواب' },
      { en: 'Torn leather upholstery, heavy carpet stains, or sagging headliner', ar: 'تمزق في جلد المقاعد أو هبوط قماش سقف السيارة' },
      { en: 'Driver seat heating or cooling ventilation elements not warming up', ar: 'تعطل نظام تدفئة أو تبريد المقاعد الأمامية' },
    ],
    descriptionEn: 'Check seat track mechanisms, seatbelt tensioners, interior switches, console trim, and headliner condition.',
    descriptionAr: 'فحص مجاري المقاعد، أحزمة الأمان، مفاتيح التحكم، وفرش السقف والأرضيات.',
  },
  {
    id: 'body_exterior',
    nameEn: 'Body Panels & Exterior Paint',
    nameAr: 'الهيكل والدهان الخارجي',
    systemCategoryEn: 'Bumpers, Fenders, Hood & Paint Finish',
    systemCategoryAr: 'الصدامات، الرفارف، الكبوت، وجودة طلاء الهيكل',
    icon: '🚗',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 50, y: 22 },
    cardOffset: { x: -40, y: -80 },
    symptoms: [
      { en: 'Deep paint scratches, swirl marks, or clear coat peeling', ar: 'خدوش غائرة في الطلاء أو تقشر في طبقة الورنيش الشفاف' },
      { en: 'Door dings, fender dents, or bumper cover scuffs and cracks', ar: 'صدمات ودقات في الأبواب أو شروخ في الصدامات' },
      { en: 'Uneven bumper panel gaps or loose wheel arch splash guard', ar: 'فروقات وفضاوه غير متناسقة بين أجزاء الصدام والرفرف' },
      { en: 'Hood or rear tailgate hydraulic lift struts failing to hold up', ar: 'مساعدات الكبوت أو الشنطة ضعيفة وتسقط عند فتحها' },
      { en: 'Exterior plastic trim molding faded, cracked, or unclipped', ar: 'بهتان أو كسر في زوائد الفايبر والديكورات البلاستيكية' },
    ],
    descriptionEn: 'Inspect body panel alignment, paint thickness, exterior dent severity, and bumper mounting clips.',
    descriptionAr: 'فحص استقامة الفواصل، سماكة الدهان، الصدمات السطحية، وكلبسات الصدامات.',
  },
  {
    id: 'infotainment',
    nameEn: 'Audio, Display & Navigation',
    nameAr: 'الشاشة والوسائط والصوتيات',
    systemCategoryEn: 'Touchscreen, Audio, Bluetooth & Camera',
    systemCategoryAr: 'الشاشة اللمسية، البلوتوث، الكاميرا، ونظام الصوت',
    icon: '📻',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 52, y: 32 },
    cardOffset: { x: 40, y: -75 },
    symptoms: [
      { en: 'Center touchscreen freezing, rebooting, or displaying black screen', ar: 'شاشة اللمس تعلق أو تعيد التشغيل أو شاشة سوداء' },
      { en: 'Bluetooth failing to pair or repeatedly dropping phone connection', ar: 'فشل اقتران البلوتوث أو انقطاع الاتصال المتكرر' },
      { en: 'Backup camera showing fuzzy, distorted, or flickering video feed', ar: 'كاميرا الرجوع للخلف مشوشة أو تومض بصورة غير واضحة' },
      { en: 'Audio speakers crackling, buzzing, or missing bass sound', ar: 'خشونة وزنة في السماعات أو انقطاع الصوت من جانب واحد' },
      { en: 'Apple CarPlay or Android Auto disconnecting intermittently', ar: 'انقطاع متكرر في اتصال أبل كاربلاي أو أندرويد أوتو' },
    ],
    descriptionEn: 'Test head unit firmware, touchscreen digitizer response, speaker channels, and rear camera feed.',
    descriptionAr: 'فحص تحديث الشاشة، استجابة اللمس، قنوات السماعات، وجودة إشارة الكاميرا.',
  },
  {
    id: 'adas_sensors',
    nameEn: 'ADAS & Parking Sensors',
    nameAr: 'الحساسات وأنظمة المساعدة',
    systemCategoryEn: 'Radar, Cameras, Sonar & Driver Assist',
    systemCategoryAr: 'الرادار الأمامي، حساسات الركن، وكاميرات المساعدة',
    icon: '📡',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 16, y: 58 },
    cardOffset: { x: -30, y: -80 },
    symptoms: [
      { en: 'Parking distance sensor beeping continuously with no obstacle', ar: 'حساسات الركن تصدر صفيراً مستمراً دون وجود عائق' },
      { en: 'Blind Spot Detection warning indicator amber light malfunction', ar: 'لمبة النقطة العمياء في المرايا مضيئة بعطل أو غير مفعلة' },
      { en: 'Front collision radar sensor blocked or calibration error alert', ar: 'رسالة خطأ في رادار الاصطدام الأمامي أو الحاجة لضبط' },
      { en: 'Lane Departure Warning camera unable to detect highway road lanes', ar: 'كاميرا تتبع المسار لا تتعرف على خطوط الطريق' },
      { en: 'Adaptive Cruise Control unavailable message appearing on cluster', ar: 'نظام مثبت السرعة التفاعلي غير متاح في شاشة العدادات' },
    ],
    descriptionEn: 'Calibrate front bumper radar unit, windshield ADAS camera, and ultrasonic sonar sensors.',
    descriptionAr: 'معايرة رادار الصدام، كاميرا الزجاج الأمامي، وحساسات الموجات فوق الصوتية.',
  },
  {
    id: 'drivetrain',
    nameEn: 'Drivetrain, Axles & Differential',
    nameAr: 'العكوس والدفرنس والمحاور',
    systemCategoryEn: 'CV Axles, Universal Joints & Differential',
    systemCategoryAr: 'عكوس العجلات، عمود الكردان، والدفرنس الخلفي',
    icon: '🔄',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 60, y: 62 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Clicking, popping, or snapping sound from front wheels when turning', ar: 'صوت طقطقة عند لف عجلة القيادة أثناء السير والدوران' },
      { en: 'Torn CV axle rubber boot throwing dark grease inside wheel rim', ar: 'قطع كاوتشة العكس وتسريب الشحم الأسود داخل الجنط' },
      { en: 'Howling, humming, or whining noise from rear differential under load', ar: 'صوت ونّة من الدفرنس الخلفي يزداد مع زيادة السرعة' },
      { en: 'Loud metallic clunk felt when shifting between Park and Drive', ar: 'طقة ورزعة قوية عند التبديل بين P و D' },
      { en: 'Heavy vibration under acceleration caused by worn driveshaft joints', ar: 'اهتزاز قوي عند التسارع بسبب تآكل صلايب عمود الكردان' },
    ],
    descriptionEn: 'Inspect constant velocity (CV) boots, drive axle play, differential gear backlash, and transfer case fluid.',
    descriptionAr: 'فحص كاوتشات العكوس، فضاوه أعمدة الدفع، وخلوص تروس الدفرنس.',
  },
  {
    id: 'chassis_frame',
    nameEn: 'Chassis, Frame & Underbody',
    nameAr: 'الشاسيه والعفشة السفلية',
    systemCategoryEn: 'Subframe, Control Arms & Skid Plates',
    systemCategoryAr: 'الشاسيه، القنطرة السفلية، ميزان الاتزان، وحماية المحرك',
    icon: '🛡️',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 45, y: 72 },
    cardOffset: { x: -30, y: -80 },
    symptoms: [
      { en: 'Loud creaking or groaning sound over driveways and speed humps', ar: 'صوت تزييق وتخشيب من أسفل السيارة عند المطبات ومطالع الجراج' },
      { en: 'Worn lower control arm bushings with cracked rubber or play', ar: 'تشقق وتآكل جلب المقصات السفلية ووجود فراغ ملحوظ' },
      { en: 'Loose or dragging engine lower plastic splash shield / skid plate', ar: 'تدلي صاجة أو فيبرة حماية المحرك واحتكاكها بالطريق' },
      { en: 'Visible surface rust or corrosion pitting along underbody chassis rails', ar: 'صدأ أو تآكل في عوارض الشاسيه السفلية وأرضية السيارة' },
      { en: 'Wheel hub bearing roaring hum growing louder when curving at speed', ar: 'صوت خشونة من رمان بلي العجل يرتفع عند الميل في المنحنيات' },
    ],
    descriptionEn: 'Inspect structural frame rails, subframe crossmember mounts, sway bar end links, and wheel hub bearings.',
    descriptionAr: 'فحص استقامة الشاسيه، كراسي القنطرة، ميزان الاتزان، ورمان بلي الصرة.',
  },
  {
    id: 'hybrid_ev',
    nameEn: 'Hybrid & EV High-Voltage System',
    nameAr: 'منظومة الهايبرد والكهرباء عالية الجهد',
    systemCategoryEn: 'Traction Battery, Inverter & Charging Port',
    systemCategoryAr: 'بطارية الهايبرد، الانفرتر، ومنفذ الشحن الكهربائي',
    icon: '🔋',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 62, y: 50 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Significant drop in electric driving range per full battery charge', ar: 'نقص حاد وسريع في مدى القيادة الكهربائية لكل شحنة' },
      { en: 'High-Voltage system warning indicator or Turtle power reduction mode', ar: 'إضاءة تحذير النظام الهجين أو علامة السلحفاة لتحديد العزم' },
      { en: 'Vehicle fails to initiate charging or charge port latch remains stuck', ar: 'السيارة ترفض بدء الشحن أو قفل مقبس الشاحن عالق' },
      { en: 'Regenerative braking feels grabby, weak, or triggers cluster warning', ar: 'فرملة استعادة الطاقة الكهربائية خشنة أو غير منتظمة' },
      { en: 'Hybrid inverter coolant loop overheat warning or pump error', ar: 'ارتفاع حرارة انفرتر الهايبرد أو تعطل طلمبة تبريده' },
    ],
    descriptionEn: 'Test high-voltage pack cell balancing, charging port interlock circuit, inverter coolant, and isolation resistance.',
    descriptionAr: 'قياس توازن خلايا بطارية الجهد العالي، دورة تبريد الانفرتر، وعزل المنظومة.',
  },
  {
    id: 'airbags_safety',
    nameEn: 'Airbags & SRS Safety Systems',
    nameAr: 'الوسائد الهوائية وأنظمة الأمان',
    systemCategoryEn: 'Airbag Modules, Sensors & Seatbelts',
    systemCategoryAr: 'الوسائد الهوائية، حساسات الصدمات، وحزام الأمان الذكي',
    icon: '🦺',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 54, y: 28 },
    cardOffset: { x: 40, y: -75 },
    symptoms: [
      { en: 'SRS Airbag warning light remains illuminated continuously on dash', ar: 'لمبة الإيرباج (SRS) مضيئة باستمرار في الطبلون' },
      { en: 'Passenger Airbag OFF light stays lit with an adult passenger seated', ar: 'مؤشر إيقاف إيرباج الراكب مضاء رغم جلوس راكب بالكرسي' },
      { en: 'Steering wheel clock spring failure causing horn and buttons to fail', ar: 'تعطل شريط الإيرباج في الطارة مسبباً توقف الكلاكس والأزرار' },
      { en: 'Seatbelt buckle chime chimes continuously with belt latched securely', ar: 'جرس حزام الأمان يرن باستمرار رغم تثبيت الحزام في مكانه' },
      { en: 'Crash impact sensor fault code stored in SRS safety control module', ar: 'تسجيل كود عطل في حساس صدمات مقدمة أو جانب السيارة' },
    ],
    descriptionEn: 'Scan SRS restraint control module, verify clock spring continuity, and inspect seatbelt pre-tensioner resistance.',
    descriptionAr: 'فحص كمبيوتر الوسائد الهوائية، شريط الطارة، وكبسولات شد أحزمة الأمان.',
  },
  {
    id: 'doors_locks',
    nameEn: 'Doors, Locks & Windows',
    nameAr: 'الأبواب والأقفال والسنترلوك',
    systemCategoryEn: 'Latches, Regulators, Central Locking & Sunroof',
    systemCategoryAr: 'كالون الأبواب، ماكينات الزجاج، السنترلوك، وفتحة السقف',
    icon: '🔐',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 63, y: 38 },
    cardOffset: { x: 45, y: -75 },
    symptoms: [
      { en: 'Power window glass moves very slowly, screeches, or drops off track', ar: 'زجاج الباب يرتفع ببطء شديد أو يصدر صوت صرير حاد' },
      { en: 'Door lock actuator buzzes or clicks but door remains unlocked', ar: 'صوت طرمبة السنترلوك تعمل لكن الباب لا يقفل أو يفتح' },
      { en: 'Smart touch keyless door handle sensor unresponsive to touch', ar: 'بصمة مقبض الباب الخارجي لا تفتح السيارة عند اللمس' },
      { en: 'Trunk lid or power tailgate latch fails to open or latch completely shut', ar: 'كالون الشنطة الخلفية لا يفتح أو لا يغلق بإحكام' },
      { en: 'Panoramic sunroof leaking rainwater or sticking when sliding open', ar: 'تسريب مياه من فتحة السقف أو تعليقها أثناء الفتح والغلق' },
    ],
    descriptionEn: 'Inspect power window regulator cables, door latch actuator motors, keyless antennas, and sunroof drain tubes.',
    descriptionAr: 'فحص وايرات ماكينات الزجاج، مواتير السنترلوك، ومجارير فتحة السقف.',
  },
  {
    id: 'turbo',
    nameEn: 'Turbocharger & Air Intake',
    nameAr: 'التوربو ونظام سحب الهواء',
    systemCategoryEn: 'Forced Induction & Breathing',
    systemCategoryAr: 'نظام الشحن القسري وتنفس المحرك',
    icon: '🌀',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 34, y: 36 },
    cardOffset: { x: -30, y: -85 },
    symptoms: [
      { en: 'Whistling or siren noise from the engine bay under load', ar: 'صفير عالي من التوربو أثناء السحب' },
      { en: 'Turbo lag: long delay before the car pulls', ar: 'تأخر استجابة التوربو وبطء في السحب' },
      { en: 'Blue smoke from the exhaust at high revs', ar: 'دخان أزرق من العادم عند الدوران العالي' },
      { en: 'Boost warning light or limp mode on the motorway', ar: 'لمبة تحذير الشحن أو دخول وضع الطوارئ' },
      { en: 'Oil in the intercooler pipe or intake hose', ar: 'زيت داخل ماسورة الانتركولر أو خرطوم السحب' },
    ],
    descriptionEn: 'Inspect turbo shaft play, wastegate actuator, boost pressure sensor, intercooler pipework, and air filter restriction.',
    descriptionAr: 'فحص خلوص عمود التوربو، الويست جيت، حساس ضغط الشحن، مواسير الانتركولر، وفلتر الهواء.',
  },
  {
    id: 'clutch',
    nameEn: 'Clutch & Gearshift Linkage',
    nameAr: 'الدبرياج ووصلات نقل السرعات',
    systemCategoryEn: 'Torque Engagement',
    systemCategoryAr: 'نقل العزم والاشتباك',
    icon: '🛞',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 45, y: 52 },
    cardOffset: { x: -20, y: -70 },
    symptoms: [
      { en: 'Clutch slips: revs rise but the car does not pull', ar: 'الدبرياج يزحلق والعداد يرتفع بدون سحب' },
      { en: 'Burning smell after climbing a hill or heavy traffic', ar: 'رائحة احتراق بعد الطلوع أو الزحام' },
      { en: 'Pedal feels soft, sinks to the floor, or stays down', ar: 'دواسة الدبرياج خفيفة أو تنزل للأرض ولا ترجع' },
      { en: 'Grinding or refusal when selecting first or reverse', ar: 'صوت طحن أو رفض دخول الأولى أو الرجوع' },
      { en: 'Judder from standstill when releasing the pedal', ar: 'اهتزاز عند التحرك من الثبات مع رفع الدواسة' },
    ],
    descriptionEn: 'Inspect clutch disc wear, pressure plate, release bearing, master and slave cylinder, and gearshift cable adjustment.',
    descriptionAr: 'فحص اسطوانة الدبرياج، الضاغط، رومان بلي، اسطوانة رئيسية ومساعدة، وضبط كابل نقل السرعات.',
  },
  {
    id: 'belts',
    nameEn: 'Belts, Chains & Pulleys',
    nameAr: 'السيور والجنازير والطارات',
    systemCategoryEn: 'Accessory & Timing Drive',
    systemCategoryAr: 'نقل الحركة للملحقات والتوقيت',
    icon: '➰',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 28, y: 43 },
    cardOffset: { x: -35, y: -80 },
    symptoms: [
      { en: 'Loud squealing on cold start or when the A/C engages', ar: 'صفير عالي عند التشغيل البارد أو تشغيل التكييف' },
      { en: 'Rattling or chain noise from the front of the engine', ar: 'صوت خبط أو جنزير من مقدمة المحرك' },
      { en: 'Cracked, glazed, or frayed accessory belt', ar: 'سير الملحقات متشقق أو لامع أو مهترئ' },
      { en: 'Battery light on with the belt still fitted', ar: 'لمبة البطارية مضيئة والسير موجود' },
      { en: 'Wobbling pulley or tensioner moving under load', ar: 'اهتزاز الطارة أو الشداد أثناء التحميل' },
    ],
    descriptionEn: 'Inspect serpentine belt condition, tensioner and idler bearings, timing belt or chain stretch, and pulley alignment.',
    descriptionAr: 'فحص حالة السير، الشداد والبكر، شد جنزير أو سير التوقيت، واستقامة الطارات.',
  },
  {
    id: 'filters',
    nameEn: 'Filters: Air, Oil, Fuel & Cabin',
    nameAr: 'الفلاتر: هواء وزيت وبنزين ومكيف',
    systemCategoryEn: 'Filtration & Service Items',
    systemCategoryAr: 'التنقية وبنود الصيانة الدورية',
    icon: '🧊',
    color: '#0284c7',
    glowColor: 'rgba(2, 132, 199, 0.4)',
    hotspotPct: { x: 38, y: 33 },
    cardOffset: { x: -25, y: -85 },
    symptoms: [
      { en: 'Weak airflow from the vents with the fan on full', ar: 'ضعف الهواء من الفتحات رغم أعلى سرعة مروحة' },
      { en: 'Musty or dusty smell inside the cabin', ar: 'رائحة عفن أو تراب داخل المقصورة' },
      { en: 'Fuel starvation or hesitation above a certain speed', ar: 'تقطيع أو ضعف سحب بعد سرعة معينة' },
      { en: 'Oil service light on or oil darker than it should be', ar: 'لمبة الصيانة مضيئة أو الزيت أسود مبكرًا' },
      { en: 'Air filter visibly clogged with dust or leaves', ar: 'فلتر الهواء مسدود بالتراب أو الأوراق' },
    ],
    descriptionEn: 'Inspect and replace engine air, cabin, oil and fuel filters against the workshop service interval.',
    descriptionAr: 'فحص وتغيير فلاتر الهواء والمقصورة والزيت والبنزين حسب فترة الصيانة.',
  },
];

export function getSubsystemById(id: string): InspectableSubsystem | undefined {
  const norm = id.toLowerCase().trim();
  if (norm === 'battery') return CAR_SUBSYSTEMS.find((s) => s.id === 'electrical');
  return CAR_SUBSYSTEMS.find((s) => s.id === norm);
}
